fixed a massive conflicting/hidden files and changes
FACN8/Donator pull request #20
Opened 2020-03-10 14:00 UTC by LinaQh95

2020-03-10 14:05 UTC, LinaQh95 commented
#6 #21 #1 
In general, this is setting up sign up page to make it easier for the user to register to the website and see all their donations details and history.

2020-03-10 14:26 UTC, Karyum requested changes
right now all the text fields are not connected to a state, do you want to do it now ? or later on when you connect it to the API ? (both are the same)

2020-03-10 14:26 UTC, Karyum commented on src/App.jsx
> +        <SignUp/>
delete this line to avoid merge conflicts with other pull requests

2020-03-10 14:26 UTC, Karyum commented on src/components/SignUpInputs/index.jsx
> +//                     className="input-form"
do you need these comments ? if not can we delete them?

2020-03-10 14:26 UTC, Karyum commented on src/components/SignUpInputs/index.jsx
> +import Checkbox from '@material-ui/core/Checkbox';
too many components here are all of them even used?

2020-03-10 14:26 UTC, Karyum commented on src/components/SignUpInputs/index.jsx
> +      <CssBaseline />
what does this do?

2020-03-10 14:26 UTC, Karyum commented on src/components/SignUpInputs/style.css
> +    /* align-content: space-between; */
remove commented out code in css

2020-03-10 14:26 UTC, Karyum commented on src/components/SignUpInputs/style.css
> +/* position: absolute; */
this too and there is much more

2020-03-10 14:26 UTC, Karyum commented on src/screens/SignUp/style.css
> +    /* position: absolute; */
again commented out code in this file

2020-03-11 14:38 UTC, Karyum approved these changes

2020-03-11 14:38 UTC, merged