connects to the server to get data
FACN8/Donator pull request #41
Opened 2020-03-18 17:14 UTC by FrancisA2000

2020-03-18 20:59 UTC, Karyum requested changes

2020-03-18 20:59 UTC, Karyum commented on src/components/OrgBubble/index.jsx
> +            })();
what is this why ?

2020-03-18 20:59 UTC, Karyum commented on src/components/OrgBubble/index.jsx
> +      })}
```suggestion
      {orgInfo.map((org, i) => (
          <div key={i} className="org_bubble">
            <a href={org.fb_url}>
              <img src={org.img_url}></img>
            </a>
          </div>
        )
      )}
```

2020-03-18 20:59 UTC, Karyum commented on src/components/OrgStatistic/index.jsx
> +import { getRequest } from "../../utils/axios.js";
again your prettier, you really need to fix it, either you or @92yo

2020-03-18 20:59 UTC, Karyum commented on src/components/OrgStatistic/index.jsx
> +            })();
again why ?

2020-03-19 11:02 UTC, FrancisA2000 commented on src/components/OrgStatistic/index.jsx
> +            })();
error handeling

2020-03-19 13:30 UTC, Karyum approved these changes

2020-03-19 13:31 UTC, merged